from __future__ import annotations

from datetime import datetime
from typing import Protocol

from datalens.domain.session import Session


class SessionStore(Protocol):
    def create(self, now: datetime | None = None) -> Session: ...
    def get(self, session_id: str, now: datetime | None = None) -> Session | None: ...
    def touch(self, session_id: str, now: datetime | None = None) -> Session | None: ...
    def update(self, session: Session) -> Session: ...
    def delete(self, session_id: str) -> Session | None: ...
    def expire(self, now: datetime | None = None) -> list[Session]: ...
    def expired(self, now: datetime | None = None) -> list[Session]: ...
    def all(self) -> list[Session]: ...
    def try_begin_turn(self, session_id: str, now: datetime | None = None) -> Session | None: ...
    def end_turn(self, session_id: str) -> None: ...
